### ISSUE TITLE
A couple of oldies but goodies

### ISSUE THREAD

**Issue by max-arnold** [rufuspollock/awesome-crypto-critique#28]
1. https://blog.gardeviance.org/2013/11/a-spoiler-for-future-bitcoin.html A prediction about Bitcoin made in 2013 by Simon Wardley. Particularly interesting bits are related to taxation issues
2. https://hackernoon.com/ten-years-in-nobody-has-come-up-with-a-use-case-for-blockchain-ee98c180100 Very good comparison of various blockchain use-cases and how they are better solved by existing technologies
3. https://medium.com/@kaistinchcombe/decentralized-and-trustless-crypto-paradise-is-actually-a-medieval-hellhole-c1ca122efdec A sequel for the previous blog post
4. https://thecorrespondent.com/655/blockchain-the-amazing-solution-for-almost-nothing/84495599980-95473476 And the last piece is from 2020

**Comment by rufuspollock** [comment]
@max-arnold these are great - thank-you!

**Comment by rufuspollock** [comment]
@max-arnold i've added the first of these - if you were up for a PR I'd welcome adding the rest (or i can do it if you would like).
